In [ ]:
#Predict the price of a house in USA using Regression

In [ ]:
#import all libraries

In [34]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#load data

In [35]:
df=pd.read_csv('USA_Housing.csv')

In [36]:
df.head()

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0      79545.458574             5.682861                   7.009188   
1      79248.642455             6.002900                   6.730821   
2      61287.067179             5.865890                   8.512727   
3      63345.240046             7.188236                   5.586729   
4      59982.197226             5.040555                   7.839388   

   Avg. Area Number of Bedrooms  Area Population         Price  \
0                          4.09     23086.800503  1.059034e+06   
1                          3.09     40173.072174  1.505891e+06   
2                          5.13     36882.159400  1.058988e+06   
3                          3.26     34310.242831  1.260617e+06   
4                          4.23     26354.109472  6.309435e+05   

                                             Address  
0  208 Michael Ferry Apt. 674\nLaurabury, NE 3701...  
1  188 Johnson Views Suite 079\nLake Kathleen, CA...  
2  9127 Elizabeth Stravenue\nDanieltown, WI 06482...  
3                          USS Barnett\nFPO AP 44820  
4                         USNS Raymond\nFPO AE 09386

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Avg. Area Income              5000 non-null   float64
 1   Avg. Area House Age           5000 non-null   float64
 2   Avg. Area Number of Rooms     5000 non-null   float64
 3   Avg. Area Number of Bedrooms  5000 non-null   float64
 4   Area Population               5000 non-null   float64
 5   Price                         5000 non-null   float64
 6   Address                       5000 non-null   object 
dtypes: float64(6), object(1)
memory usage: 273.6+ KB


In [38]:
df.describe()

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
count       5000.000000          5000.000000                5000.000000   
mean       68583.108984             5.977222                   6.987792   
std        10657.991214             0.991456                   1.005833   
min        17796.631190             2.644304                   3.236194   
25%        61480.562388             5.322283                   6.299250   
50%        68804.286404             5.970429                   7.002902   
75%        75783.338666             6.650808                   7.665871   
max       107701.748378             9.519088                  10.759588   

       Avg. Area Number of Bedrooms  Area Population         Price  
count                   5000.000000      5000.000000  5.000000e+03  
mean                       3.981330     36163.516039  1.232073e+06  
std                        1.234137      9925.650114  3.531176e+05  
min                        2.000000       172.610686  1.593866e+04  
25%                        3.140000     29403.928702  9.975771e+05  
50%                        4.050000     36199.406689  1.232669e+06  
75%                        4.490000     42861.290769  1.471210e+06  
max                        6.500000     69621.713378  2.469066e+06

In [39]:
df.columns

Index(['Avg. Area Income', 'Avg. Area House Age', 'Avg. Area Number of Rooms',
       'Avg. Area Number of Bedrooms', 'Area Population', 'Price', 'Address'],
      dtype='object')

In [7]:
print(df['Avg. Area Income'].unique())
print(df['Avg. Area House Age'].unique())
print(df['Avg. Area Number of Rooms'].unique())
print(df['Avg. Area Number of Bedrooms'].unique())
print(df['Area Population'].unique())
print(df['Price'].unique())

[79545.45857432 79248.64245483 61287.06717866 ... 63390.6868855
 68001.33123509 65510.58180367]
[5.68286132 6.00289981 5.86588984 ... 7.25059061 5.53438842 5.99230531]
[7.00918814 6.73082102 8.51272743 ... 4.80508098 7.13014386 6.7923361 ]
[4.09 3.09 5.13 3.26 4.23 4.04 3.41 2.42 2.3  6.1  4.1  4.49 3.1  2.27
 4.37 4.01 3.12 4.3  5.12 5.49 4.07 2.1  4.31 6.34 4.33 2.03 4.   3.04
 3.24 4.42 5.36 6.29 6.   2.07 3.01 2.39 2.5  2.17 6.3  4.43 4.44 6.32
 3.18 6.35 3.22 2.13 4.02 6.36 3.32 4.12 6.41 5.08 3.06 2.28 4.2  4.32
 5.43 3.13 3.28 3.27 3.08 3.17 3.15 6.25 3.43 4.38 6.16 4.28 4.11 6.24
 3.35 4.48 3.2  3.07 3.39 3.38 6.06 3.3  3.46 3.33 4.41 2.38 2.37 3.45
 2.02 2.14 2.23 2.44 2.29 4.19 6.04 5.28 5.1  5.45 4.36 2.05 6.39 4.45
 4.22 6.44 4.35 3.37 6.2  6.19 2.49 2.04 4.46 5.15 3.21 6.45 3.44 2.18
 3.49 6.26 4.14 4.27 5.04 4.06 6.4  3.25 5.33 3.   2.47 3.31 3.14 4.18
 5.07 6.11 2.   5.3  4.26 2.31 3.48 3.29 3.11 3.36 2.15 6.18 5.25 4.47
 5.21 4.15 6.37 6.49 6.28 2.09 4.29 6.21 2.08 4.24

In [40]:
df.isna().sum()

Avg. Area Income                0
Avg. Area House Age             0
Avg. Area Number of Rooms       0
Avg. Area Number of Bedrooms    0
Area Population                 0
Price                           0
Address                         0
dtype: int64

In [10]:
# get all columns except 'Address' which is non numeric

In [43]:
df.columns[:-1]

Index(['Avg. Area Income', 'Avg. Area House Age', 'Avg. Area Number of Rooms',
       'Avg. Area Number of Bedrooms', 'Area Population', 'Price'],
      dtype='object')

In [ ]:
#scaling

In [44]:
from sklearn.preprocessing import StandardScaler
s_scaler = StandardScaler()

In [45]:
usa_house_scaled = s_scaler.fit_transform(df[df.columns[:-1]])
usa_house_scaled = pd.DataFrame(usa_house_scaled, columns=df.columns[:-1])
usa_house_scaled.head()

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0          1.028660            -0.296927                   0.021274   
1          1.000808             0.025902                  -0.255506   
2         -0.684629            -0.112303                   1.516243   
3         -0.491499             1.221572                  -1.393077   
4         -0.807073            -0.944834                   0.846742   

   Avg. Area Number of Bedrooms  Area Population     Price  
0                      0.088062        -1.317599 -0.490081  
1                     -0.722301         0.403999  0.775508  
2                      0.930840         0.072410 -0.490211  
3                     -0.584540        -0.186734  0.080843  
4                      0.201513        -0.988387 -1.702518

In [46]:
usa_house_scaled.describe()

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
count      5.000000e+03         5.000000e+03               5.000000e+03   
mean      -1.069145e-17         2.836967e-18              -3.916145e-16   
std        1.000100e+00         1.000100e+00               1.000100e+00   
min       -4.765584e+00        -3.361975e+00              -3.730214e+00   
25%       -6.664724e-01        -6.606490e-01              -6.846171e-01   
50%        2.075434e-02        -6.852312e-03               1.502401e-02   
75%        6.756386e-01         6.794590e-01               6.742146e-01   
max        3.670725e+00         3.572745e+00               3.750297e+00   

       Avg. Area Number of Bedrooms  Area Population         Price  
count                  5.000000e+03     5.000000e+03  5.000000e+03  
mean                  -2.029016e-16    -3.146816e-16 -1.326328e-16  
std                    1.000100e+00     1.000100e+00  1.000100e+00  
min                   -1.605598e+00    -3.626413e+00 -3.444336e+00  
25%                   -6.817833e-01    -6.810902e-01 -6.641384e-01  
50%                    5.564767e-02     3.616311e-03  1.690042e-03  
75%                    4.122077e-01     6.748621e-01  6.772856e-01  
max                    2.041039e+00     3.371219e+00  3.503412e+00

In [47]:
#spliting data into features and target

In [48]:
X = usa_house_scaled.drop(['Price'],axis=1)

y= usa_house_scaled[['Price']]

In [62]:
X.head()

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0          1.028660            -0.296927                   0.021274   
1          1.000808             0.025902                  -0.255506   
2         -0.684629            -0.112303                   1.516243   
3         -0.491499             1.221572                  -1.393077   
4         -0.807073            -0.944834                   0.846742   

   Avg. Area Number of Bedrooms  Area Population  
0                      0.088062        -1.317599  
1                     -0.722301         0.403999  
2                      0.930840         0.072410  
3                     -0.584540        -0.186734  
4                      0.201513        -0.988387

In [63]:
y.head()

Price
0 -0.490081
1  0.775508
2 -0.490211
3  0.080843
4 -1.702518

In [ ]:
#Train test split

In [49]:
from sklearn.model_selection import train_test_split

In [50]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33,random_state=100)

In [64]:
X_train.shape

(3350, 5)

In [65]:
y_train.shape

(3350, 1)

In [66]:
X_test.shape

(1650, 5)

In [67]:
y_test.shape

(1650, 1)

In [ ]:
#linear regression

In [52]:
from sklearn.linear_model import LinearRegression
lm_scaled = LinearRegression()
lm_scaled.fit(X_train, y_train)

LinearRegression()

In [57]:
y_pred= lm_scaled.predict(X_test)

In [58]:
y_pred

array([[-1.1852244 ],
       [ 0.93668032],
       [ 0.25346055],
       ...,
       [ 0.40793672],
       [-0.41882281],
       [ 1.20892355]])

In [68]:
len(y_pred)

1650

In [69]:
X_test.head()

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
789          -0.614638            -0.748480                   0.095146   
2507          1.436929             0.569228                  -1.719911   
2376         -0.389711             0.463761                   0.488777   
1378         -1.019840            -1.021289                   0.805638   
598          -0.020630             0.332016                  -0.625576   

      Avg. Area Number of Bedrooms  Area Population  
789                       0.331171        -1.097913  
2507                      0.306860         0.756612  
2376                     -0.544021         0.291426  
1378                      1.149639         1.706606  
598                      -0.511607        -1.561325

In [79]:
X_test.head(1)

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
789         -0.614638             -0.74848                   0.095146   

     Avg. Area Number of Bedrooms  Area Population  
789                      0.331171        -1.097913

In [73]:
y_pred1= lm_scaled.predict(X_test.head(1))

In [74]:
y_pred1

array([[-1.1852244]])

In [75]:
y_test.head(1)

Price
789 -1.221425

In [80]:
X_test.head(2)

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
789          -0.614638            -0.748480                   0.095146   
2507          1.436929             0.569228                  -1.719911   

      Avg. Area Number of Bedrooms  Area Population  
789                       0.331171        -1.097913  
2507                      0.306860         0.756612

In [76]:
y_pred2= lm_scaled.predict(X_test.head(2))

In [77]:
y_pred2

array([[-1.1852244]])

In [78]:
y_test.head(2)

Price
789  -1.221425
2507  1.101377